import SectionEnd from "../Components/Section-End/SectionEnd";
import MainTitle from "../Components/Main-title/MainTitle";
import ParaSection from "../Components/Special-Paragraph/ParaSection";
import AnimatedSection from "../Components/AnimatedSection/AnimatedSection";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

import {
  faLinkedin,
  faGithub,
  faGoogleDrive,
  faWhatsapp,
  faHtml5,
  faCss3,
  faJs,
  faReact,
  faSass,
  faBootstrap,
} from "@fortawesome/free-brands-svg-icons";

import {
  faPhone,
  faDownload,
  faLink,
  faCalendar,
  faInbox,
  faAddressCard,
  faCertificate,
  faSignature,
  faArrowUp,
  faHandScissors,
  faCheckDouble,
  faEquals,
  faHandPaper,
  faHandRock,
  faMapMarkerAlt,
  faMobile,
  faAngleRight,
  faAngleLeft,
  faGamepad,
  faMobileScreen,
  faLocationDot,
  faQuoteLeft,
  faQuoteRight,
  faAngleDown,
  faEnvelope,
  faCircleCheck,
  faP,
  faT,
  faRocket,
  faCode,
  faFlask, // Jest (testing)
  faLayerGroup, // Next.js (layered architecture)
  faCodeMerge, // Redux (state management)
  faPaintRoller, // Tailwind (styling)
  faWind,
} from "@fortawesome/free-solid-svg-icons";

export {
  ParaSection,
  FontAwesomeIcon,
  SectionEnd,
  MainTitle,
  AnimatedSection,
  faPhone,
  faCalendar,
  faEnvelope,
  faInbox,
  faAddressCard,
  faCertificate,
  faSignature,
  faArrowUp,
  faCircleCheck,
  faCheckDouble,
  faHandPaper,
  faEquals,
  faHandRock,
  faHandScissors,
  faGithub,
  faGoogleDrive,
  faLinkedin,
  faMapMarkerAlt,
  faMobile,
  faAngleLeft,
  faAngleRight,
  faGamepad,
  faLocationDot,
  faMobileScreen,
  faWhatsapp,
  faQuoteLeft,
  faQuoteRight,
  faCss3,
  faHtml5,
  faJs,
  faP,
  faReact,
  faSass,
  faT,
  faBootstrap,
  faCodeMerge,
  faFlask,
  faLayerGroup,
  faPaintRoller,
  faLink,
  faAngleDown,
  faDownload,
  faCode,
  faRocket,
  faWind,
};
